version: '3'

services:
  app:
    build: . # Build and run ./Dockerfile
    working_dir: /app
    volumes:
      - .:/app # Always mount the current directory in /app to ensure that the app source code lives there